development:
  dialect: postgres
  database: omegle
  user: postgres
  password: 13488431
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:13488431@127.0.0.1:5432/omegle_test"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:13488431@127.0.0.1:5432/omegle_production"}}